### ISSUE TITLE
I don't know what's happening!

### ISSUE THREAD

**Issue by mineo210** [neoneggplant/EggShell#37]
MultiSession> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/username/EggShell/src/server/server.py", line 146, in multiServerListen
    if session.uid == self.sessions[sx].uid:
AttributeError: 'NoneType' object has no attribute 'uid'

**Comment by neoneggplant** [comment]
try latest commit?

**Comment by mineo210** [comment]
yeah
