### ISSUE TITLE
Getting error when client connects to server.

### ISSUE THREAD

**Issue by yannip1234** [neoneggplant/EggShell#40]
'something went wrong'
Error:
"Traceback (most recent call last):
  File "eggshell.py", line 108, in <module>
    main()
  File "eggshell.py", line 104, in main
    menu()
  File "eggshell.py", line 55, in menu
    choose[option]()
  File "eggshell.py", line 90, in menuStartMultiServer
    server.multiServer(sp[0],sp[1]);
  File "/Users/USERNAME/Documents/Folders/EggShell/src/server/server.py", line 208, in multiServer
    socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect( (host,port))
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: an integer is required"

**Comment by neoneggplant** [comment]
what did you type right before the crash?

**Comment by yannip1234** [comment]
Steps I did:
1. cd in to EggShell Folder. 
2. 'python EggShell.py'
3. Created server
4. Entered command on another computer on LAN
5. The error shows when computer connects.

**Comment by neoneggplant** [comment]
try the new release, a lot has changed, let me know if it fixed your issue, if not, I will help debug with you

**Comment by arechiksn0w** [comment]
i try new update still have error Trackback(most resent call last)
File "eggshell.py". line 7. in <module> 
import base64

**Comment by neoneggplant** [comment]
what is the full error? @arechiksn0w

**Comment by arechiksn0w** [comment]
can help me to complate eggshell.py on ios terminal?
