### ISSUE TITLE
"device unrecognized"

### ISSUE THREAD

**Issue by IAmWolfie** [neoneggplant/EggShell#5]
I think this is caused by any connection that isn't from Safari/an iPhone/iDevice.
Any fix?
`
←[0;36m[*]  ←[0;97mConnecting to 123.125.143.65
←[0;36m[*]  ←[0;97mdevice unrecognized
D573BA5A4EFFC3FB629308

←[0;36m[*]  ←[0;97mWaiting For Target...
←[0;36m[*]  ←[0;97mSending Payload
Traceback (most recent call last):
  File "eggshell.py", line 744, in <module>
    main()
  File "eggshell.py", line 741, in main
    interactiveMenu()
  File "eggshell.py", line 733, in interactiveMenu
    choose[option]()
  File "eggshell.py", line 527, in menuCreateScript
    promptServerRun(sp[0],sp[1])
  File "eggshell.py", line 507, in promptServerRun
    singleServer(host,port)
  File "eggshell.py", line 476, in singleServer
    session.listen(1,host,port)
  File "eggshell.py", line 618, in listen
    conn.send(preload)
  File "D:\Python27\lib\socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
socket.error: [Errno 9] Bad file descriptor

D:\Downloads\EggShell-master>`

**Comment by nerdtron123** [comment]
let me try to replicate

**Comment by MbrooGit** [comment]
I have the same issue with iphone 4. Url opened with safari
