### ISSUE TITLE
Cannot get past 'Establishing Secure Connection...'

### ISSUE THREAD

**Issue by hsaevol** [neoneggplant/EggShell#83]
Hello I am using the current build on linux. When I try to connect my iOS 11.0.3 I get hung up at 'Establishing Secure Connection...' I have traced the execution and pasted below. Any suggestion, need help.

[*] Listening on port 4444...
server.py(151):         try:
server.py(152):             conn, addr = s.accept()
 --- modulename: socket, funcname: accept
socket.py(206):         sock, addr = self._sock.accept()

socket.py(207):         return _socketobject(_sock=sock), addr
 --- modulename: socket, funcname: __init__
socket.py(190):         if _sock is None:
socket.py(192):         self._sock = _sock
socket.py(193):         for method in _delegate_methods:
socket.py(194):             setattr(self, method, getattr(_sock, method))
socket.py(193):         for method in _delegate_methods:
socket.py(194):             setattr(self, method, getattr(_sock, method))
socket.py(193):         for method in _delegate_methods:
socket.py(194):             setattr(self, method, getattr(_sock, method))
socket.py(193):         for method in _delegate_methods:
socket.py(194):             setattr(self, method, getattr(_sock, method))
socket.py(193):         for method in _delegate_methods:
socket.py(194):             setattr(self, method, getattr(_sock, method))
socket.py(193):         for method in _delegate_methods:
socket.py(194):             setattr(self, method, getattr(_sock, method))
socket.py(193):         for method in _delegate_methods:
server.py(157):         hostAddress = addr[0]
server.py(158):         if self.is_multi == False:
server.py(159):             h.info_general("Connecting to "+hostAddress)
 --- modulename: helper, funcname: info_general
helper.py(32):     print "{0}[*] {1}{2}".format(COLOR_INFO,WHITE,string)
[*] Connecting to 192.168.01.01
server.py(160):         conn.send(identification_shell_command)
server.py(161):         device_arch = conn.recv(128).strip()
server.py(162):         if not device_arch:
server.py(165):         try:
server.py(166):             bash_stager, executable = self.craft_payload(device_arch)
 --- modulename: server, funcname: craft_payload
server.py(92):         if not self.host:
server.py(94):         if not self.port:
server.py(96):         payload_parameter = h.b64(json.dumps({"ip":self.host,"port":self.port,"debug":1}))
 --- modulename: __init__, funcname: dumps
__init__.py(240):     if (not skipkeys and ensure_ascii and
__init__.py(241):         check_circular and allow_nan and
__init__.py(242):         cls is None and indent is None and separators is None and
__init__.py(243):         encoding == 'utf-8' and default is None and not sort_keys and not kw):
__init__.py(244):         return _default_encoder.encode(obj)
 --- modulename: encoder, funcname: encode
encoder.py(194):         if isinstance(o, basestring):
encoder.py(207):         chunks = self.iterencode(o, _one_shot=True)
 --- modulename: encoder, funcname: iterencode
encoder.py(222):         if self.check_circular:
encoder.py(223):             markers = {}
encoder.py(226):         if self.ensure_ascii:
encoder.py(227):             _encoder = encode_basestring_ascii
encoder.py(230):         if self.encoding != 'utf-8':
encoder.py(236):         def floatstr(o, allow_nan=self.allow_nan,
encoder.py(237):                 _repr=FLOAT_REPR, _inf=INFINITY, _neginf=-INFINITY):
encoder.py(259):         if (_one_shot and c_make_encoder is not None
encoder.py(260):                 and self.indent is None and not self.sort_keys):
encoder.py(261):             _iterencode = c_make_encoder(
encoder.py(262):                 markers, self.default, _encoder, self.indent,
encoder.py(263):                 self.key_separator, self.item_separator, self.sort_keys,
encoder.py(264):                 self.skipkeys, self.allow_nan)
encoder.py(270):         return _iterencode(o, 0)
encoder.py(208):         if not isinstance(chunks, (list, tuple)):
encoder.py(210):         return ''.join(chunks)
 --- modulename: helper, funcname: b64
helper.py(52):     return base64.b64encode(s)
 --- modulename: base64, funcname: b64encode
base64.py(54):     encoded = binascii.b2a_base64(s)[:-1]
base64.py(55):     if altchars is not None:
base64.py(57):     return encoded
server.py(97):         if device_arch in self.macos_architectures:
server.py(110):         elif device_arch in self.ios_architectures:
server.py(111):             if self.is_multi == False:
server.py(112):                 h.info_general("Detected iOS")
 --- modulename: helper, funcname: info_general
helper.py(32):     print "{0}[*] {1}{2}".format(COLOR_INFO,WHITE,string)
[*] Detected iOS
server.py(113):             f = open("resources/esplios", "rb")
server.py(114):             payload = f.read()
server.py(115):             f.close()
server.py(120):             "/tmp/espl "+payload_parameter+" 2>/dev/null &\n"
server.py(121):             return (instructions,payload)
server.py(172):         if self.is_multi == False:
server.py(173):             h.info_general("Sending Payload")
 --- modulename: helper, funcname: info_general
helper.py(32):     print "{0}[*] {1}{2}".format(COLOR_INFO,WHITE,string)
[*] Sending Payload
server.py(174):         conn.send(bash_stager)
server.py(175):         conn.send(executable)
server.py(176):         conn.close()

**Comment by LiesRapas** [comment]
Yea, me neither...

**Comment by neoneggplant** [comment]
are you running eggshell inside of a virtual machine?

**Comment by LiesRapas** [comment]
Nah, i'm running it on a raspberry pi, with kali linux, but i encountered
the same issues on mac os high sierra when i installed it on my macbook pro

2018-03-25 22:41 GMT+02:00 Lucas Jackson <notifications@github.com>:

**Comment by hhdevteam** [comment]
@neoneggplant it's because the openssl libraries are not being statically linked in the xcode project properly. It's dynamic, and if the target hasn't installed openssl via macports or brew then the dylibs aren't available. I have this working now in an xcode project, i'll tidy and put in a PR.

**Comment by LiesRapas** [comment]
Thanks a lot ! it worked when i installed openssl !

2018-03-27 4:31 GMT+02:00 hhdevteam <notifications@github.com>:

**Comment by hsaevol** [comment]
Looking forward to exploring and all the neat features!,

**Comment by neoneggplant** [comment]
@hhdevteam Awesome that you found that, I was having a hard time recreating the issue!

**Comment by neoneggplant** [comment]
Can anyone who is having the issue let me know if this works? I believe the library is now statically linked in esplmacos 
https://github.com/neoneggplant/EggShell/tree/dev

**Comment by keshaipad** [comment]
@neoneggplant 
Something wrong with that one "dev" branch I think...
```
Initializing server...
Traceback (most recent call last):
  File "eggshell.py", line 158, in <module>
    eggshell = EggShell()
  File "eggshell.py", line 11, in __init__
    self.server = server.Server()
  File "/root/eggShellDev/modules/server.py", line 21, in __init__
    self.modules_python = self.import_modules("modules/commands/python")
  File "/root/eggShellDev/modules/server.py", line 30, in import_modules
    for mod in os.listdir(path):
OSError: [Errno 2] No such file or directory: 'modules/commands/python'
```

**Comment by neoneggplant** [comment]
@keshaipad sorry about that, just pushed a fix, try now :)

**Comment by keshaipad** [comment]
Hehe. There now another problem. 
I try to connect - but nothing happened. 
And when exit from MultiHandler - get some error about ssl
```
Menu:

    1): Start Server
    2): Start MultiHandler
    3): Create Payload
    4): Exit

EggShell> 2
[*] SET LHOST (Leave blank for 125.5.247.62)>
[*] LHOST = 125.5.247.62
[*] SET LPORT (Leave blank for 4444)>2525
[*] LPORT = 2525
[*] Listening on port 2525...
[*] Type "help" for commands

MultiHandler> exit
[*] Cleaning up...
[*] SSL error: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol end start multihandler
```

**Comment by keshaipad** [comment]
**Linux:** (server)
_Python 2.7.6
OpenSSL 1.0.1f 6 Jan 2014_

**Mac:** (client)
_Python 2.7.10
OpenSSL 0.9.8zg 14 july 2015_

**Comment by computer00776** [comment]
So do we need to install openssl on target ?
if so can someone tell me the command to do so please.
Thanks guys

**Comment by neoneggplant** [comment]
the dev branch should have the esplmacos ssl library statically linked

**Comment by computer00776** [comment]
Sorry buddy
Still not working
Stuck on establishing secure connection even with the tree/dev version

**Comment by neoneggplant** [comment]
is the target a linux machine? Openssl will have to be installed

**Comment by computer00776** [comment]
no its a mac machine
do i still need to install Openssl ?

**Comment by molomilo** [comment]
Hello, thank you for your Eggshell.
I still have'nt a solution for the etablishing secure connection. New?
I am on kali to iphone 4 in 7.1.2 jaillbreak.
Open SSL is installed on the iphone but nothing works. Even the version with DEV does'nt work.
Need help.

**Comment by KodiacSecurity** [comment]
As stated above the ssl library is statically linked in the dev-branch. It solves the problem. Tested on Sierra, Yosemite and Snow leopard. 

If not, fall back to https://github.com/neoneggplant/EggShell/tree/dd9f71eb3cc59ebb2d0e3bf27fa6affa0f47b993

**Comment by shegner** [comment]
I connect with Kali Linux (up to date) to an older iPad with iOS 9.3.5 (jail breaked, MTerminal). I tried master and dev branch. No Luck. Eggshell hangs on 'Establishing Secure Connection...' So I tried the older version as KodiacSecurity proposed. That work's, but only a few commands are working like sysinfo or alert. Camera, open app etc. are NOT working. Is there a version, I can use, so that taking pictures and open apps are working?
