### ISSUE TITLE
UnboundLocalError: local variable 'result' referenced before assignment

### ISSUE THREAD

**Issue by nbshenxm** [neoneggplant/EggShell#92]
When I try to open a connection on a ubuntu 16.04 machine, the connection can't be established with following error messages (I'm using eggshell version 3.1.1):

[*] Establishing Secure Connection...
Traceback (most recent call last):
  File "eggshell.py", line 159, in <module>
    eggshell.menu()
  File "eggshell.py", line 143, in menu
    self.menu()
  File "eggshell.py", line 142, in menu
    choose[option]()
  File "eggshell.py", line 59, in start_single_server
    self.server.start_single_handler()
  File "/home/parallels/Documents/eggshell_3.1.1/modules/server.py", line 90, in start_single_handler
    session.interact()
  File "/home/parallels/Documents/eggshell_3.1.1/modules/session.py", line 33, in interact
    command_modules = self.server.get_modules(self.type)
  File "/home/parallels/Documents/eggshell_3.1.1/modules/server.py", line 44, in get_modules
    result.update(self.modules_universal)
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by nbshenxm** [comment]
BTW, this issue wouldn't occur if you use eggshell version 3.0.0. I guess get_modules function need to be modified in version 3.1.1.

**Comment by neoneggplant** [comment]
Will push an update for this asap

**Comment by Blazejnr** [comment]
please can i get the link for backdating to 3.0.0 because i have the same issue.
